title: 天翼云盘签到记录
description: 自动签到记录和统计

# 排除文件
exclude:
  - README.md
  - main.py
  - requirements.txt
  - .env
  - .git/
  - .github/

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge 
